# Generated by Django 3.1.7 on 2021-03-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='color',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Kindergarden', 'Kindergarden'), ('Child', 'Child')], default='Child', max_length=15),
        ),
    ]
