# Generated by Django 3.1.7 on 2021-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210331_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
