pipeline {
    agent { 
        docker{
            image 'python:3.9.1' 
        } 
    }
    stages 
    {
        stage('build') 
        {
            steps 
            {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python -m pip install --upgrade pip --user'
                    sh 'python -m pip install -r requirements.txt'

                    sh 'python manage.py migrate'
                    sh 'python manage.py makemigrations'
                    sh 'python manage.py migrate'
                    //pipeline build command to check later
                }
            }
        }
        stage('Test') 
        {
            steps 
            {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python manage.py test'
                }
            }
        }

        stage('Metric 1 -  coverage') {
			steps {
					withEnv(["HOME=${env.WORKSPACE}"]) {
                        sh 'pip install coverage'
						sh 'python -m coverage run manage.py test'
						sh 'python -m coverage report --fail-under=50'
				}
			}
		}

       stage('Metric 2 - pylint python code convention') {
			steps {
					withEnv(["HOME=${env.WORKSPACE}"]) {
                        sh 'pip install pylint'
                        sh 'pip install pylint-django'
						sh 'python -m pylint --fail-under=1 matching_game game accounts AdminInitialize.py'
					}
				
			}
		}

		
    }
    post{
		failure{
			mail to: 'olgrsy@gmail.com , razmor5@gmail.com , barazenkot3@gmail.com , noam56744756@gmail.com',
			subject: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
		success{
			mail to: 'olgrsy@gmail.com , razmor5@gmail.com , barazenkot3@gmail.com , noam56744756@gmail.com',
			subject: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
    }

}