pipeline {
    agent { 
        docker{
            image 'python:3.9.1' 
        } 
    }
    stages {
        stage('build') 
        {
            steps 
            {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python -m pip install --upgrade pip --user'
                    sh 'python -m pip install -r requirements.txt'

                    sh 'python manage.py migrate'
                    sh 'python manage.py makemigrations'
                    sh 'python manage.py migrate'
                    //pipeline build command to check later
                }
            }
        }
        stage('Test') 
        {
            steps 
            {
                withEnv(["HOME=${env.WORKSPACE}"]) {
                    sh 'python manage.py test'
                }
            }
        }
    }
    post {
		failure{
			mailto: 'barazenkot3@gmail.com',
			subject: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "Failed: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
		success{
			mailto: 'barazenkot3@gmail.com',
			subject: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']",
			body: "SUCCESS: Job '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']: Check console output at '${env.BUILD_URL}' '${env.JOB_NAME}' ['${env.BUILD_NUMBER}']"
		}
		
	}
}